<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account registration at ' => '',
    'BMI' => 'IMC',
    'BMI Calculator' => 'Calculadora IMC',
    'BMI Calculator - Register' => 'Calculadora IMC - Registro',
    'Breyin' => 'Breyin',
    'Calculate' => 'Calcular',
    'Classification' => 'Clasificacion',
    'Error!' => 'Error!',
    'Height' => 'Altura',
    'Home' => 'Inicio',
    'ID' => 'ID',
    'Id User' => 'Id de usuario',
    'Login' => 'Iniciar sesion',
    'Registration Date' => 'Fecha de registro',
    'Show Historical' => 'Ver Historico',
    'Show historical' => 'Ver Historico',
    'Signup' => 'Registrarse',
    'Successful registration!' => 'Registro exitoso!',
    'This application calculates the body mass index with your height and weight, start rigth now and know your BMI:  ' => 'Esta aplicacion calcula el indice de masa corporal con su altura y peso, comience ahora y conozca su IMC: ',
    'Weight' => 'Peso',
    'Welcome to BMI Calculator!' => 'Bienvenido a Calculadora IMC',
];
