<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account registration at ' => '',
    'BMI' => 'IMC',
    'BMI Calculator' => 'Calculadora IMC',
    'BMI Calculator - Register' => 'Calculadora IMC - Registro',
    'Breyin' => 'Breyin',
    'Calculate' => 'Calcular',
    'Classification' => 'Clasificacion',
    'Error!' => 'Error!',
    'Height' => 'Altura',
    'Home' => 'Inicio',
    'ID' => 'ID',
    'Id User' => 'Id de usuario',
    'Login' => 'Iniciar sesion',
    'Registration Date' => 'Fecha de registro',
    'Show Historical' => 'Ver Historico',
    'Show historical' => 'Ver Historico',
    'Signup' => 'Registrarse',
    'Successful registration!' => 'Registro exitoso!',
    'This application calculates the body mass index with your height and weight, start rigth now and know your BMI:  ' => 'Esta aplicacion calcula el indice de masa corporal con su altura y peso, comience ahora y conozca su IMC: ',
    'Weight' => 'Peso',
    'Welcome to BMI Calculator!' => 'Bienvenido a Calculadora IMC',
    'Please fill out the following fields to signup:' => 'Por favor, complete los siguientes campos para registrarse:',
    'Please fill out the following fields to login:' => 'Por favor, complete los siguientes campos para iniciar sesion:',
    "Passwords don't match" => 'Las contraseñas no coinciden',
    'Name' => 'Nombres',
    'Last Name' => 'Apellidos',
    'Email' => 'Correo',
    'Password' => 'Contraseña',
    'Confirm Password' => 'Confirmar Contraseña',
    'Remember me' => 'Recordarme',
    'Need new verification email?' => '¿Necesita un nuevo correo de verificacion?',
    'Resend' => 'Reenviar',
    'reset it' => 'restablecerla',
    'If you forgot your password you can' => 'Si olvido su contraseña puede',
    'Incorrect email or password.' => 'Correo o contraseña incorrecta',
    'Please choose your new password:' => 'Porfavor elige tu nueva contraseña:',
    'Save' => 'Guardar',
    'Hello ' => 'Hola ',
    'Follow the link below to verify your email:' => 'Siga el enlace de abajo para verificar su correo:',
    'Follow the link below to reset your password:' => 'Siga el enlace de abajo para restablecer su contraseña',
    'There is no user with this email address.' => 'No hay usuario con esta direccion de correo',
    'Please fill out your email. A link to reset password will be sent there.' => 'Por favor ingrese su correo. Un enlace para restablecer la contraseña será enviado allí.',
    'Send' => 'Enviar',
    'Request password reset' => 'Restablecer contraseña',
    'Please contact us if you think this is a server error. Thank you.' => 'Por favor póngase en contacto con nosotros si cree que se trata de un error del servidor. Gracias.',
    'The above error occurred while the Web server was processing your request.' => 'Ocurrió un error mientras el servidor web estaba procesando su solicitud.',
    'Please fill out your email. A verification email will be sent there.' => 'Por favor ingrese su correo. Un correo de verificación será enviado allí.',
    'Resend verification email' => 'Reenviar correo de verificacion',
];
